# Generated by Django 4.0.5 on 2022-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthOnline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(null=True, upload_to='PatientImage'),
        ),
    ]
